package org.ajdeveloppement.webserver.data;

import javax.annotation.Generated;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Map;
import java.util.HashMap;
import org.ajdeveloppement.commons.persistence.sql.QResults;
import org.ajdeveloppement.commons.persistence.sql.QField;
import org.ajdeveloppement.commons.persistence.ObjectPersistenceException;

@Generated(value="Generated by ajcommons")
@SuppressWarnings({"nls","javadoc"})
public class T_DatabaseParameters {
	public static final String TABLE_NAME = "AJWEBSERVER.PARAM";

	/**
	 * Object Binder for dbVersion field of table AJWEBSERVER.PARAM
	 */
	public static final QField<java.lang.Integer> DBVERSION = new QField<>(TABLE_NAME,"dbVersion");

	/**
	 * Object Binder for APPREVISION field of table AJWEBSERVER.PARAM
	 */
	public static final QField<java.lang.Integer> APPREVISION = new QField<>(TABLE_NAME,"APPREVISION");

	/**
	 * Object Binder for DEFAULT_LANG field of table AJWEBSERVER.PARAM
	 */
	public static final QField<java.lang.String> DEFAULT_LANG = new QField<>(TABLE_NAME,"DEFAULT_LANG");

	/**
	 * Object Binder for dbUUID field of table AJWEBSERVER.PARAM
	 */
	public static final QField<java.util.UUID> DBUUID = new QField<>(TABLE_NAME,"dbUUID");

	/**
	 * Return all instance in database as QResults iterator
	 */
	public static QResults<DatabaseParameters, Void> all() {
		return QResults.from(DatabaseParameters.class);
	}

}